
run_name: SwinUNETR_predict
output_dir: ./predicts/${run_name}

# dataset
dataset: BML2D
pkl_list: 'dataset.pkl'
data_path: "./dataset/BMLClosing"
weight_path: /projectnb/aicv/Shihua_Qin/BMLSeg2D/outputs/Seg_2D_BML_BML2D/ckpts
model_version: UnetPlusPlus_diceCELoss_BMLonly_Dice

# data preprocessing
# label_type: label_bml
a_min: 0.0
a_max: 255.0
b_min: 0.0
b_max: 1.0
roi_x: 256
roi_y: 256

# model
model_name: BasicUNetPlusPlus
spatial_dims: 2
in_channels: 1
out_channels: 1
features: [32, 32, 64, 128, 256, 32]
dropout: 0.3

tta: 0

# randomness
seed:
rank: 0
gpu: 1