
run_name: SwinUNETR_predict
output_dir: ./predicts/${run_name}

# dataset
dataset: BML2D
pkl_list: 'dataset.pkl'
data_path: "./dataset/BMLClosing"
weight_path: /projectnb/aicv/Shihua_Qin/BMLSeg2D/outputs/Seg_2D_BML_BML2D/ckpts
model_version: SwinUnetr_diceCELoss_BMLonly_Dice

# data preprocessing
# label_type: label_bml
a_min: 0.0
a_max: 255.0
b_min: 0.0
b_max: 1.0
roi_x: 256
roi_y: 256

# model
model_name: SwinUNETR
in_channels: 1
out_channels: 1
depths: [2, 2, 2, 2]
num_heads: [3, 6, 12, 24]
feature_size: 24
drop_rate: 0.1
attn_drop_rate: 0.0
dropout_path_rate: 0.0
use_checkpoint: 1
spatial_dims: 2
use_v2: 0

tta: 0

# randomness
seed:
rank: 0
gpu: 1