# architecture
arch: Seg_2D

# wandb
proj_name: ${arch}_BML
run_name: ${proj_name}_${dataset}
wandb_id:
disable_wandb: 0

# dataset
label_type: label_bml
dataset: BML2D
pkl_list: 'dataset.pkl'
data_path: "./dataset"
output_dir: ./outputs/${run_name}
ckpt_dir: "${output_dir}/ckpts"

# data preprocessing
a_min: 0.0
a_max: 255.0
b_min: 0.0
b_max: 1.0
roi_x: 256
roi_y: 256
RandFlipd_prob: 0.4
RandRotate90d_prob: 0.4
RandScaleIntensityd_prob: 0.1
num_samples: 4
val_num_samples: 2
hte: 0

# trainer
trainer_name: UNetTrainer
batch_size: 8
val_batch_size: 36
start_epoch: 0
warmup_epochs: 50
epochs: 500
workers: 8
resume:

# model
spatial_dims: 2
in_channels: 1
out_channels: 2
channels: [16, 32, 64, 128, 256]
strides: [2, 2, 2, 2]
num_res_units: 2
ch1weight: 0.8
ch2weight: 0.2

# logging
print_freq: 5
save_ckpt_num: 5
eval_freq: 2


# optimizer
type: adamw
lr: 6.4e-3
beta1: 0.9
beta2: 0.95
weight_decay: 0.05

# randomness
seed:
rank: 0
gpu: 1